## TidyTuesday WK1 media_franchises ##
## jonathon_mifsud ##
## 03/07/19 ##

library(tidyverse)
library(hrbrthemes)
library(ggthemes)
library(ggchicklet)

## Reading in the file ##
media_franchises <- readr::read_csv(
    "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-02/media_franchises.csv")

# Looking at the data I think this week I would like to make a bar-plot. Franchise has a length of 103 unique titles,
# which may be too lengthy to analyse in this form. Instead, I aim to make a  of the total revenue separated by year.
# I will segment each year to show the contributions of each each type of original media.

## CLEANING ##

# delete duplicates
media_franchises <-
  media_franchises[!duplicated(media_franchises),]

# We have alot of years to work with. Instead of looking at a subset of this I will try creating multiple bins.
#We have 52 individual years so we could break this evenly into 13 bins. I am sure there is a better way to generate the labels!

media_franchises$year_created <-
  cut(media_franchises$year_created,
    breaks = 13,
    labels = c(
      "1924-1931",
      "1931-1938",
      "1938-1945",
      "1945-1951",
      "1951-1958",
      "1958-1965",
      "1965-1972",
      "1972-1979",
      "1979-1986",
      "1986-1992",
      "1992-1999",
      "1999-2006",
      "2006-2013"))

year_counts <- media_franchises %>%
  group_by(revenue_category, year_created) %>%
  summarise(total_yearly_revenue_by_category = round(sum(revenue)),
            media_count = n())

## PLOT ##

#This barplot was inspired by a post and wonderful barplot tutorial by @hrbrmstr https://rud.is/b/2019/06/30/make-refreshing-segmented-column-charts-with-ggchicklet/ using the package ggchicklet

p <- year_counts %>%
  ggplot(aes(year_created, total_yearly_revenue_by_category, fill = revenue_category)) +
  geom_chicklet(width = 0.75) +
  scale_y_comma(position = "right") +
  coord_flip() +
  ggthemes::scale_fill_tableau('Superfishel Stone', name = NULL) +
  labs(
    x = NULL ,
    y = "Total revenue generated overtime (in billions)",
    fill = NULL,
    title = "Revenue Generated by Media Franchise Powerhouses",
    subtitle = "By Year of Franchise Inception",
    caption = "Source Wikipedia, Plot by @jonathon_mifsud"
  ) +
  theme_ipsum_rc(grid = "X") +
  theme(legend.position = "bottom")

ggsave(
  "plots/plot_2019-07-03.png",
  width = 29,
  height = 21,
  units = "cm",
  dpi = "retina"
)

## I have also made a version with the bar-plot ordered ##
year_counts_ordered <- media_franchises %>%
  group_by(revenue_category, year_created) %>%
  summarise(total_yearly_revenue_by_category = round(sum(revenue)),
            media_count = n()) %>%
  mutate(
    year_created = fct_relevel(
      year_created,
      "1992-1999",
      "1972-1979",
      "1999-2006",
      "1979-1986",
      "1924-1931",
      "1986-1992",
      "2006-2013",
      "1965-1972",
      "1958-1965",
      "1938-1945",
      "1945-1951",
      "1951-1958",
      "1931-1938"))
#I am sure there is a better way to do this

year_counts_ordered <- year_counts_ordered %>%
  mutate(year_created = fct_rev(year_created))# after manually inputting the order I realised that it was lowest value first so I am reversing it so we get the higher revenes first.

p2 <- year_counts_ordered %>%
  ggplot(aes(year_created, total_yearly_revenue_by_category, fill = revenue_category)) +
  geom_chicklet(width = 0.75) +
  scale_y_comma(position = "right") +
  coord_flip() +
  ggthemes::scale_fill_tableau('Superfishel Stone', name = NULL) +
  labs(
    x = NULL ,
    y = "Total revenue generated overtime (in billions)",
    fill = NULL,
    title = "Revenue Generated by Media Franchise Powerhouses",
    subtitle = "By Year of Franchise Inception",
    caption = "Source Wikipedia, Plot by @jonathon_mifsud"
  ) +
  theme_ipsum_rc(grid = "X") +
  theme(legend.position = "bottom")
